apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # Alpha environment runs fewer replicas
  replicas: 1
  template:
    metadata:
      labels:
        environment: alpha
    spec:
      containers:
        - name: frontend
          env:
            - name: NEXT_PUBLIC_ENVIRONMENT
              value: "alpha"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
